### ISSUE TITLE
CVS?

### ISSUE THREAD

**Issue by kevinsea** [kirkhansen/covid-vaccine-finder#2]
Hi, I noticed your code reaches out to the CVS API that provides detailed information about vaccine availability, but I don't see CVS on your site result tonight.  Did you have success calling this API?  (I was using a chromedriver approach and ran into their bot detection).  I ended up using the simpler API that provides a Go/NoGo answer by city.  Did you have success calling the detailed API?

**Comment by kirkhansen** [comment]
It appey to be working with their more detailed api. If you look right now, there are a couple cvs entries.

**Comment by kevinsea** [comment]
I see one, thank you.

**Comment by kevinsea** [comment]
I know people that need to take the J&J one, that script will help track that down.   Thank you.
